= `wrut`
:toc: macro
:toc-title: 
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:warning-caption: :warning:
endif::[]

A utility to manage project templates.

NOTE: This document does not reflect the current state of the project, which is undergoing a complete rewrite.

[discrete]
== Table of Contents 

toc::[]

== Feature Overview

* Project template creation and management.
* Project creation and management.
* Macro expansion when creating new projects from existing templates.
* Tags to better organize and filter templates and projects.

== Setup

The `wrut --setup a` command will initialize two directories: `~/.wrut` and
`~/.config/wrut`. The `~/.wrut` directory is used to store application data
(also referred to as the "data directory") and the `~/.config/wrut` directory
is used to store configuration data (also referred to as the "configuration
directory," or just the "config directory").

See `wrut --help` for more information about the `--setup` command.

== Data Storage 

The data directory contains the `templates`, `projects`, `tags`, and `.obj`
subdirectories. The `.obj` directory is used by `wrut` to store internal
representations of templates for faster project generation. The other three are
used to store data regarding templates, projects, and tags respectively.

The `templates` and `projects` directories contain symbolic links to actual
template or project directories. The `tags` directory is a little more complex,
in that it stores directories named after each tag, and each of these
directories contains a `templates` and `projects` directory, which each contain
an empty file named after the appropriate template/project.

Example `~/.wrut` directory structure:
[source,sh]
----
.wrut
├── projects
│   ├── Essay         # symlink; could point to ~/foo/bar, doesn't matter
│   └── wrut           # file name and real path are considered separately
├── tags
│   ├── Programming 
│   │   ├── projects
│   │   │   └── wrut
│   │   └── templates
│   │       └── Rust
│   └── Writing
│       ├── projects
│       │   └── Essay
│       └── templates
│           └── LaTeX
└── templates
    ├── Rust          # symlink; same as with projects
    └── LaTeX
----

=== Configuration

WARNING: Not yet implemented.

Configuration files are stored in the `~/.config/wrut` configuration directory.

== Command-Line Usage

You can run `wrut --help` to get the full help message.

You can also run `wrut <TYPE> <COMMAND> --help` to get more detailed
information about a given command.

=== Basic Template Usage

=== Basic Project Generation

WARNING: Not yet implemented.

=== Macros 

WARNING: Not yet implemented.

=== Tags

